<?php
define('Google_API', 'YOUR GOOGLE CLOUD API KEY FOR BACKEND HERE - ENSURE TO ENABLE CLOUD TRANSLATE AND GEOCODING FUNCTION');
define('GMap_Key', 'YOUR GOOGLE CLOUD API KEY FOR FRONTEND HERE - ENSURE TO ENABLE JSMAP');
define('IPinfo_API', 'YOUR IPINFO.IO API KEY HERE');
define('OWM_API', 'YOUR OPEN WEATHER MAP ONECALL 3.0 API KEY HERE');
define('GPT_API', 'YOUR OPENAI APIKEY HERE - ALTERNATIVE MODELS & SOULTIONS AVAILABLE AND WILL BE UPDATED IN FURTHER UPDATES');
define('AMap_API', 'OPTIONAL - YOUR CHINA AUTOMAPS API KEY HERE');
define('AMap_SafetyKey', 'OPTIONAL - YOUR CHINA AUTOMAPS API SAFETYKEY HERE');
define('COZE_API', 'IGNORE ME');

// !!! Input your cloud service api keys above !!!